# Generated by Django 5.0.6 on 2024-06-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailingmessage_owner_mailingsettings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='next_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующая дата отправки'),
        ),
    ]
