# Generated by Django 5.0.6 on 2024-06-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailingsettings_next_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='next_datetime',
        ),
    ]
